config/routes.rb
Rails.application.routes.draw do


  resources :stores

  resources :categories do
    end

  devise_for :users
  resources :users

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/sell'

  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  resources :products do
    

    collection do
      get :search
    end
  end


  root "pages#home"
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :user
  has_many :products

  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  def search
    @categories = Category.all
    if params[:category].blank? && params[:search].blank?
      @stores = Store.all.order(created_at: :desc).page(params[:page]).per(20)
    else
      @stores = Store.search(params)
    end
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    @store.user_id = current_user.id
    @store.user.username = current_user.username
    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :description, :location)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= simple_form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
    <small>Add a brand name or just a name for your store</small>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control"%>
    <small>Add a description to your shop. This could be a summarized description of your brand.</small>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control"%>
    <small>Where is your store located</small>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: "form-control"%>
    <small>Store Contact Phone</small>
  </div>

  <div class="actions">
    <%= f.submit class: "button-other" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<div class="section-home"><br>
  <div class="container">
    <h3 class="page-header">Edit store details.</h3>
    <div class="col-md-8 col-md-offset-2">
      <%= render 'form' %>
      <hr>
      <%= link_to 'Show', @store %> |
      <%= link_to 'Back', stores_path %><br><br>
    </div>
  </div>

</div>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.description %></td>
        <td><%= store.location %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<div class="section-home"><br>
  <div class="container">
    <h3 class="page-header">Please complete the form to get started</h3>
    <div class="col-md-8 col-md-offset-2">
      <%= render 'form' %>
      <hr>
      <%= link_to 'Back', stores_path %><br><br>
    </div>
  </div>

</div>

app/views/stores/show.html.erb
<br>
<div class="store-banner">
  <div class="container">
    <div class="">
      <div class="row">
        <div class="col-md-10 col-sm-8 col-xs-12">
          <h3><%= @store.name %></h3>
          <h4><%= @store.description %></h4>
        <span><i class="fa fa-map-marker" aria-hidden="true"><%= @store.location %></i></span>
          <h5><%= @store.created_at.strftime("Joined %d/%Y") %></h5>
          <% if (user_signed_in?) && (current_user == @store.user) %>
            <%= link_to 'Edit your shop', edit_store_path(@store), class: "btn button-default" %>
            <%= link_to "Add item", new_product_path, class: "btn button-other"%>
          <% else %>
            <%= link_to 'Back', stores_path %>
          <% end %>

        </div>
        <div class="col-md-2 col-sm-4">
          <h4>Owned by</h4>
          <span class= "round-image-50"><%= image_tag(@store.user.image(:thumb)) %></span>
          <h3>   <%= link_to @store.user.username , user_path %></h3>
        </div>
      </div>
    </div>
  </div>
</div>
<section>
  <div class="container">
    <div class="row">

      <div class="col-md-10 col-md-offset-1">
        <h3 class="page-header">Shop Items</h3>
        <div class="row">

            <% @store.products.each do |product| %>
              <div class="col-md-3 col-xs-6 col-sm-4 col-lg-3">
                  <div class="thumbnail">
                    <%= link_to image_tag(product.image.url(:medium)), product %>
                    <div class="caption">
                      <h3><%= link_to product.name, product %></h3>
                      <span class="amount">GHS <%= product.price %></span>

                    </div>
                  </div>
              </div>
            <% end %>

        </div>
      </div>
    </div>
  </div>

</section>