config/routes.rb
Rails.application.routes.draw do


  resources :stores

  resources :categories do
    end

  devise_for :users
  resources :users

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/sell'

  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  resources :products do
    

    collection do
      get :search
    end
  end


  root "pages#home"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_attached_file :image, styles: { large: "1000x1000#", :medium => "300x300#", :thumb => "100x100#" }, default_url: "default.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :products
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    # @category = Category.all
    @categories = Category.find(params[:id])
    subcategories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.file_field :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h3 class="page-header">All Categories</h3>
  <div class="row">
    <% @categories.each do |category| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(category.image(:medium)), category %>
          <div class="caption">
            <%= link_to category.name, category %>
          </div>
        </div>

      </div>
    <% end %>
  </div>

  <br>
</div>


<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<br><div class="">
  <div class="container-fluid">
      <h2 class="page-header" style="text-align: center;"><%= @category.name %></h2>
      <div class="row">

        <div class="container">
          <div class="col-md-3">
            <%=  image_tag(@category.image.url(:medium)) %>
            <div class="panel">
              <h3 class="page-header" style="text-align: left; margin-left: -1.5rem;">Categories</h3>
              <ul class="cat-side">
               
              </ul>
            </div>
          </div>
          <div class="col-md-9">
            <div class="row">
              <div class="col-md-3">
                <% @categories.products.each do |product| %>
                  <div class="thumbnail">
                    <%= link_to image_tag(product.image.url(:medium)), product %>
                    <div class="caption">
                      <h3><%= link_to product.name, product %></h3>
                      <span class="left" style="text-transform: uppercase;"><%= product.user.username %></span>
                      <span class="amount right"><%= number_to_currency(product.price) %></span>

                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

    <hr>
    <%= link_to 'Edit', edit_category_path(@category) %> |
    <%= link_to 'Back', categories_path %>

  </div>
</div>