config/routes.rb
Rails.application.routes.draw do


  resources :stores

  resources :categories do
    end

  devise_for :users
  resources :users

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/sell'

  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  resources :products do
    

    collection do
      get :search
    end
  end


  root "pages#home"
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles: { large: "500x500#", :medium => "200x200#", :thumb => "100x100#" }, default_url: "default.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :name, :description, :price, :location, :category_id, :image, presence: true

  belongs_to :category
  belongs_to :store


  def self.search(params)
    if params[:category].present?
      products = Product.where(category_id: params[:category].to_i)
      products = products.where("name like ? or description like ? user like", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
      # items = Item.where(params[:location], 20) is params[:location].present?
    else
      products = Product.where("name like ? or description like ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    end
    products
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /product
  # GET /product.json
  def index
    @product = Product.all
    @categories = Category.all
    @users = User.all
  end

  # GET /product/1
  # GET /product/1.json
  def show
    @categories = Category.all
    @user = User.all 
    @store = @product.store_id
  end

  def search
    @categories = Category.all
    if params[:category].blank? && params[:search].blank?
      @products = Product.all.order(created_at: :desc).page(params[:page]).per(20)
    else
      @products = Product.search(params)
    end
  end

  # GET /product/new
  def new
    @product = Product.new
    @category = Category.new
    @categories = Category.all
  end

  # GET /product/1/edit
  def edit
  end

  # POST /product
  # POST /product.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.store_id = current_user.store.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/1
  # PATCH/PUT /product/1.json
  def update
    respond_to do |format|
      if @listing.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/1
  # DELETE /product/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :location, :image, :category_id, :store_id)
    end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
    <small>Add a name to your item. eg. iPhone 7 32GB</small>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
    <small>Provide a very good description for your item. Remember good description attracts!</small>
  </div>
  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), {}, class: "form-control" %>
    <small>Select a category.</small>
  </div>
  
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
    <small>Add your item price per unit.</small>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: "form-control" %>
    <small>Where are you selling this item from?</small>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
    <small>Where are you selling this item from?</small>
  </div>

  <div class="actions">
    <%= f.submit class: "button-other" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/products/index.html.erb
<div class="section">
  <div class="container">
    <div class="">
      <div class="row">
        <% @listings.each do |listing| %>
          <div class="col-md-3">
            <div class="thumbnail">
              <%= link_to image_tag(listing.image.url(:medium)), listing %>
              <div class="caption">
                <h3><%= link_to listing.name, listing %></h3>
                <span class="left" style="text-transform: capitalize;"><%= listing.user.username %></span>
                <span class="amount right"><%= number_to_currency(listing.price) %></span>
                <br>
                <!-- <% if (user_signed_in?) && (current_user == listing.user) %>
                  <%= link_to "Edit", edit_listing_path(listing), class: "fa fa-retweet"%>
                  <%= link_to "Delete", listing, class: "fa fa-trash-o", method: :get, data: {confirm: "Are you sure?"} %>
                <% end %> -->
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <br>
    <% if user_signed_in? %>
    <%= link_to "New item", new_listing_path, class: "btn btn-primary", data: { no_turbolink: true } %>
  <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="section-home">
  <div class="container">
    <h1>Add a new item</h1>
    <%= render 'form' %>

    <hr>
    <%= link_to 'Back', products_path %>

  </div>
</div>

app/views/products/search.html.erb
<div class="section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <h3 class="sub-heading">Advanced Search</h3>
        <%= form_tag search_products_path, method: :get do  |f| %>
          <div class="form-group">
            <label>Search</label>
            <%= text_field_tag :search, nil, placeholder: "iPhone, Nike, etc.", class: "form-control"%>
          </div>
          <div class="form-group">
            <label>Category</label>
            <%= select_tag :category, options_from_collection_for_select(Category.all, :id, :name), class: "form-control" %>
          </div>
          <div class="form-group">
            <label>Location</label>
            <%= text_field_tag :location, nil, placeholder: "Accra, Kumasi, etc.", class: "form-control"%>
          </div>
          <%= submit_tag "Search", class: "button-other" %>
        <% end %>
      </div>
      <div class="col-md-10">
        <h3 class="page-header">Search results</h3>


          <% @products.each do |product| %>
          <div class="media">
            <div class="media-left">
              <%= link_to image_tag(product.image.url(:thumb)), product %>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= link_to product.name, product %></h4><br>
              <p><%= product.description%></p>
              <p><%= number_to_currency(product.price) %>  |  <span class="label label-success"><%= product.category.name %> </span> <span class="right">Sold by <%= link_to product.store.name %></span> </p>
            </div>

            <br>
          </div>
          <% end %>


          <br>
      </div>
    </div>
  </div>

</div>

app/views/products/show.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <h3 class="page-header">Sold by <%= link_to @product.store.name, store_path(@store) %></h3>
      <div class="col-md-6">
        <div class="thumbnail">
          <%= image_tag @product.image(:large) %>
        </div>
      </div>
      <div class="col-md-6"><br>
        <span class="label label-success">
          <%=  @product.category.name %>
        </span><br ><br>
        <span class="label label-danger"><%= @product.id %></span>
        <h3><%= @product.name %></h3>
        <h4> <%= number_to_currency(@product.price) %></h4>
        <label>Description:</label>
        <p  class= "well item-desc "><%= @product.description%></p>
        <i class="fa fa-map-marker" aria-hidden="true" style="font-size: 1.5rem;"> <%= @product.location %></i><br><br>
        <button type="button" name="button" class="btn btn-primary">Contact Seller</button>
        
        <button type="button" name="button" class="btn btn-primary">Add to cart</button>


        <% if (user_signed_in?) && (current_user == @user) %>
          <%= link_to "Edit", edit_product_path(@product) %>
          <%= link_to 'Back', products_path %>
          <%= link_to "Delete", @product, method: :delete, data: {confirm: "Are you sure?"} %>
        <% end %>
      </div>
      <!-- <div class="col-md-2">
        <div class="section-part">

        </div>
      </div> -->

    <div class="col-md-12">
      <br><br>
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#">Gallery</a></li>
        <li role="presentation"><a href="#">Review</a></li>
      </ul>
    </div>

  </div>
</div>