config/routes.rb
Rails.application.routes.draw do


  resources :stores

  resources :categories do
    end

  devise_for :users
  resources :users

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/sell'

  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  resources :products do
    

    collection do
      get :search
    end
  end


  root "pages#home"
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="bottom-section clearfix">
    <div class="row">
      <div class="container">
        <div class="col-md-3">
          <p>
            Buy
          </p>
            <a href="#">Registration</a>
            <a href="#">Buying</a>
            <a href="#">Stores</a>
            <a href="#">Guides</a>
        </div>
        <div class="col-md-3">
          <p>
            Sell
          </p>
            <a href="#">Learn to sell</a>
            <a href="#">Start selling</a>
            <a href="#">Sellers</a>
            <a href="#">Affiliates</a>
        </div>
        <div class="col-md-3">
          <p>
            Know us
          </p>
            <a href="#">About Us</a>
            <a href="#">Policies</a>
            <a href="#">News</a>
            <a href="#">Blog</a>
            <a href="#">Careers</a>
        </div>
        <div class="col-md-3">
          <p>
            Stay connected
          </p>
          <ul class="social-links">
            <li><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></li>
            <li><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></li>
            <li><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></li>
            <li><i class="fa fa-pinterest-p fa-2x" aria-hidden="true"></i></li>
          </ul>
        </div>
        <div class="col-md-12">
          <div class="foot-note">
            <p>&copy; 2016 claeus, Inc.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top clearfix">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "maimai", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <%= form_tag search_products_path, class: "navbar-form navbar-left", method: :get do |f| %>
           <div class="form-group has-feedback has-feedback-left">
             <%= text_field_tag :search, nil, placeholder: "What are you looking for? ", class: " form-control" %>
           </div>
           <%= submit_tag "Search", class: " button-default" %>
      <% end %>
      <ul class="nav  navbar-right">
        <% if user_signed_in? %>
          <li> <%= link_to "Start selling", pages_sell_path %></li>
          <li><%= link_to new_user_session_path do %>Favorites<% end %></li>
          <% if current_user.store %>
            <li><%= link_to "Enter Store", store_path(current_user) %> </li>
          <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle round-image-50" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View profile", user_path(current_user) %></li>
              <li><%= link_to "Messages" %></li>
              <li><%= link_to " Edit Account", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>Sign Out<% end %></li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <li> <%= link_to "Log In", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mai</title>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Raleway', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %> <br>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>


<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>